omit deprecated .secret field, allow for setting of app password in advance, do not reuse existing secret
defenseunicorns/uds-package-minio-operator pull request #33
Opened 2024-11-22 22:19 UTC by chaospuppy

## Description
This PR will allow users to specify an app password in advance, or default to a random password if a password is not provided.  Additionally, because the reuse of an existing secret was taking precedence over the random password (to avoid changing the secret every time you deploy), we check to see if a password has not been provided and there is an existing secret, in which case the password will not change between deployments.

## Related Issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-minio-operator/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-12-02 23:04 UTC, Racer159 requested changes

2024-12-02 23:04 UTC, Racer159 commented on values/tenant-values.yaml
> +  configSecret:
```suggestion
  configSecret:
```
Looking through the templates that should be in configSecret like you have it (`configuration.existingSecret` is not used)

2024-12-03 00:13 UTC, zachariahmiller approved these changes

2024-12-03 01:03 UTC, Racer159 approved these changes

2024-12-03 01:20 UTC, merged